// questionTips.ts

export const questionTips: { [key: string]: string } = {
  // --- Schritt 1: Kompetenz aufbauen ---
  '1.1': "Investieren Sie in grundlegende KI-Schulungen (z.B. durch Videos, interaktive Sessions) für Ihr Team, um ein gemeinsames Verständnis für Funktionsweisen (wie LLMs lernen) und Potenziale (Effizienz, neue Möglichkeiten) zu schaffen. Fördern Sie eine Kultur des Ausprobierens und regen Sie Diskussionen über konkrete Einsatzmöglichkeiten im eigenen Arbeitsbereich an, um Berührungsängste abzubauen.",
  '1.2': "Analysieren Sie systematisch, welche spezifischen KI-Kompetenzen für unterschiedliche Rollen (z.B. strategisches Verständnis für Führungskräfte, praktische Tool-Anwendung für operative Teams) in Ihrem Unternehmen wirklich benötigt werden. Eine genaue Bedarfsanalyse vermeidet unnötige Schulungen und fokussiert auf die Fähigkeiten, die den größten Mehrwert bringen. Dokumentieren Sie diesen Bedarf klar.",
  '1.3': "Da sich KI-Technologien alle paar Monate weiterentwickeln, sind einmalige Workshops schnell veraltet. Etablieren Sie stattdessen einen strukturierten, kontinuierlichen Prozess (z.B. Mentoring-Programme, interne Expertenrunden, kuratierte Newsletter), um das Wissen im Team aktuell zu halten und auf neue Tools und Methoden reagieren zu können.",
  '1.4': "Reine Theorie reicht nicht. Fördern Sie die praktische Anwendung von KI-Tools durch gezielte Übungen, 'Hausaufgaben' und die Integration in reale Arbeitsaufgaben. Geben Sie Mitarbeitenden die Zeit und den Raum, Tools auszuprobieren und zu lernen, wie man präzise Anweisungen (Prompts) formuliert, um nützliche Ergebnisse zu erzielen.",
  '1.5': "Etablieren Sie feste Formate für den internen Wissensaustausch über KI. Das können regelmäßige Team-Meetings, ein dedizierter Chat-Kanal, eine interne Wissensdatenbank oder 'Lunch & Learn'-Sessions sein. Ermutigen Sie Mitarbeiter ('Enthusiasten'), ihre Erfahrungen und Best Practices aktiv zu teilen.",
  '1.6': "Analysieren Sie genau, was den Kompetenzaufbau am meisten bremst: Ist es Zeitmangel, Budget, unklare Bedarfe, kulturelle Widerstände (Angst vor Veränderung) oder fehlende strategische Priorisierung durch die Führung? Gehen Sie diese größte Hürde gezielt an, z.B. durch klare Kommunikation des Nutzens, dedizierte Lernzeiten oder sichtbare Unterstützung durch das Management.",
  '1.7': "Reflektieren Sie, wie KI-Wissen derzeit im Unternehmen erworben wird. Sporadisches Ausprobieren oder der Besuch einzelner Webinare führt selten zu tiefgreifender Kompetenz. Investieren Sie in strukturierte, begleitete Lernformate (z.B. Mentoring über mehrere Monate), die kontinuierliches Lernen und praktische Anwendung fördern.",
  '1.8': "Überlegen Sie konkret: Welche wiederkehrenden Aufgaben kosten aktuell viel Zeit oder sind fehleranfällig? Das könnten die Erstellung von Meeting-Protokollen, das Verfassen von Standard-E-Mails, die Recherche von Informationen oder die Aufbereitung von Daten sein. Genau hier kann gezielter Kompetenzaufbau schnelle Erfolge bringen.",

  // --- Schritt 2: Tools gezielt einsetzen ---
  '2.1': "Bevor Sie sich auf die Suche nach KI-Tools begeben, analysieren Sie Ihre wichtigsten Geschäftsprozesse. Wo gibt es Engpässe, repetitive Aufgaben oder Verbesserungspotenziale? Eine gründliche Prozessanalyse deckt auf, wo KI wirklich sinnvoll unterstützen kann und bildet die Basis für eine gezielte Tool-Auswahl.",
  '2.2': "Lassen Sie sich nicht von Hypes oder allgemeinen Empfehlungen leiten. Die Auswahl von KI-Tools muss auf den spezifischen Anforderungen basieren, die Sie in Ihrer Prozessanalyse ermittelt haben. Der Einsatz eines unpassenden Tools (z.B. ein reines Textgenerierungs-Tool für komplexe Recherchen) führt zwangsläufig zu Frustration und schlechten Ergebnissen.",
  '2.3': "Führen Sie einen strukturierten Evaluierungsprozess für potenzielle KI-Tools ein. Definieren Sie klare Testkriterien, bilden Sie Testgruppen und erproben Sie die Tools in einer abgegrenzten Umgebung (Pilotprojekt), bevor Sie eine breitere Einführung in Erwägung ziehen. Dokumentieren Sie die Ergebnisse der Tests.",
  '2.4': "Eine erfolgreiche Tool-Einführung geht über die reine Installation hinaus. Denken Sie an die technische Integration (Schnittstellen, Datenfluss) und die organisatorische Einbindung (Anpassung von Arbeitsabläufen, Schulung der Nutzer). Nur wenn Tools gut integriert sind, werden sie effektiv genutzt.",
  '2.5': "Definieren Sie klare Kennzahlen (KPIs), um den Erfolg Ihrer eingesetzten KI-Tools zu messen (z.B. Zeitersparnis, Fehlerreduktion, Output-Steigerung). Überwachen Sie diese KPIs regelmäßig und nutzen Sie die Daten, um sowohl die Tools als auch die damit verbundenen Prozesse kontinuierlich zu verbessern und den ROI nachzuweisen.",
  '2.6': "Gehen Sie den Ursachen für Frustration auf den Grund: Sind die Tool-Ergebnisse ungenau (-> besseres Prompting/anderes Tool)? Ist die Bedienung zu komplex (-> Schulung/einfacheres Tool)? Fehlt eine klare Strategie (-> Prozessanalyse/Zieldefinition)? Sind die Tools schlecht integriert (-> technische/organisatorische Anpassung)?",
  '2.7': "Wie finden Sie neue KI-Tools? Zufälliges Ausprobieren von populären Tools ist selten effizient. Entwickeln Sie einen systematischen Ansatz: Definieren Sie klare Anforderungen basierend auf Ihren Prozessen und suchen Sie dann gezielt nach Lösungen, die diese Anforderungen erfüllen.",
  '2.8': "Welcher wiederkehrende, zeitaufwändige Prozess hat das größte Potenzial für eine KI-gestützte Verbesserung? Denken Sie an Aufgaben, die klar definierte Schritte haben und bei denen eine Automatisierung oder Unterstützung durch KI einen messbaren Nutzen (Zeitersparnis, Kostenreduktion, Qualitätssteigerung) bringen würde.",

  // --- Schritt 3: Struktur und Steuerung etablieren ---
  '3.1': "Unklare Zuständigkeiten führen oft dazu, dass KI-Initiativen im Sande verlaufen. Definieren Sie eindeutig, wer für die Entwicklung der KI-Strategie, die Auswahl und Implementierung von Tools, die Schulung der Mitarbeiter und das Controlling verantwortlich ist. Dies schafft Verbindlichkeit und ist eine zentrale Führungsaufgabe.",
  '3.2': "Formulieren Sie konkrete und messbare Ziele für Ihre KI-Projekte (z.B. 'Reduzierung der Bearbeitungszeit für X um 20% bis Ende Q3'). Allgemeine Ziele wie 'KI nutzen' sind nicht ausreichend. Nutzen Sie Kriterien wie SMART (Spezifisch, Messbar, Attraktiv, Realistisch, Terminiert), um den Erfolg nachverfolgen und steuern zu können.",
  '3.3': "Die erfolgreiche KI-Integration erfordert mehr als nur die Duldung durch die Führungsebene. Es braucht aktives Commitment: sichtbare Unterstützung, klare Priorisierung, Bereitstellung von Ressourcen und die Verankerung von KI in der Unternehmensstrategie.",
  '3.4': "Richten Sie ein regelmäßiges Reporting und Controlling für Ihre KI-Aktivitäten ein. Überwachen Sie den Fortschritt anhand der definierten KPIs und Ziele. Nutzen Sie diese Erkenntnisse, um bei Bedarf Anpassungen an der Strategie, den Tools oder den Prozessen vorzunehmen und sicherzustellen, dass die Projekte auf Kurs bleiben.",
  '3.5': "KI-Initiativen benötigen dedizierte Ressourcen. Planen Sie proaktiv und realistisch, wie viel Zeit, Budget und Personal (mit dem nötigen Know-how) für die Umsetzung erforderlich sind, und stellen Sie sicher, dass diese Ressourcen auch tatsächlich verfügbar gemacht werden. Eine rein reaktive Ressourcenvergabe führt oft zu Verzögerungen.",
  '3.6': "Wo liegt Ihre größte Herausforderung bei der Umsetzung und Steuerung von KI-Projekten? Ist es die fehlende übergreifende Strategie, die schwierige Messbarkeit des ROI, unklare Zuständigkeiten, mangelnder Support von oben oder knappe Ressourcen? Konzentrieren Sie Ihre Anstrengungen darauf, diese primäre Blockade zu lösen.",
  '3.7': "Wie werden Entscheidungen über neue KI-Projekte getroffen? Vermeiden Sie Ad-hoc-Entscheidungen, die auf der Initiative Einzelner oder kurzfristigen Gelegenheiten basieren. Implementieren Sie einen strukturierten Prozess, der sich an der übergeordneten KI-Strategie orientiert und Potenzial, Aufwand und Risiko systematisch bewertet.",
  '3.8': "Wenn Sie eine Sache sofort ändern könnten, um die Steuerung Ihrer KI-Aktivitäten zu verbessern – was wäre das? Wäre es die Ernennung eines zentralen KI-Verantwortlichen, die Einführung klarer KPIs, ein stärkeres Bekenntnis der Führung oder eine bessere Ressourcenplanung? Fokussieren Sie sich auf den größten Hebel.",

  // --- Schritt 4: Eigene KI-Produkte entwickeln ---
  '4.1': "Prüfen Sie gezielt, ob Ihr Unternehmen über einzigartige, wertvolle Datensätze verfügt, die nicht öffentlich verfügbar sind (z.B. spezifische Kundendaten, detaillierte Prozessprotokolle, proprietäre Handbücher). Solche Daten sind oft der Schlüssel zur Entwicklung differenzierender, eigener KI-Anwendungen mit hohem Mehrwert.",
  '4.2': "Eine hohe Datenqualität ist die Voraussetzung für leistungsfähige KI-Anwendungen. Bewerten Sie ehrlich die Struktur (sind Daten einheitlich erfasst?), Qualität (sind Daten korrekt und vollständig?) und Zugänglichkeit (können KI-Systeme darauf zugreifen?). Etablieren Sie Prozesse zur Datenpflege und -Governance (z.B. über Data Warehouses oder Data Lakes).",
  '4.3': "Entwickeln Sie über vage Ideen hinaus konkrete, spezifische Anwendungsfälle (Use Cases) für eigene KI-Produkte. Beschreiben Sie detailliert, welches spezifische Problem damit gelöst oder welcher konkrete Mehrwert (intern oder extern) geschaffen werden soll. Bewerten Sie diese Use Cases nach Machbarkeit und Potenzial.",
  '4.4': "Die Entwicklung eigener KI-Lösungen erfordert spezifisches technisches Know-how (z.B. Data Science, Machine Learning Engineering). Schätzen Sie realistisch ein, ob diese Kompetenzen intern vorhanden sind, aufgebaut werden können oder ob eine Zusammenarbeit mit externen Spezialisten oder Dienstleistern sinnvoller ist.",
  '4.5': "Ordnen Sie die Entwicklung eigener KI-Produkte klar in Ihrer Unternehmensstrategie ein. Handelt es sich um ein zentrales Zukunftsthema mit hoher Priorität und dedizierten Ressourcen, oder ist es eher eine Option, die bei Gelegenheit verfolgt wird? Die Priorität beeinflusst die Ressourcenallokation und das Commitment.",
  '4.6': "Was ist der wichtigste strategische Treiber für die Entwicklung einer eigenen KI-Lösung? Ist es die massive Effizienzsteigerung interner Abläufe (z.B. Automatisierung im Support), die Verbesserung der Customer Experience (z.B. personalisierte Empfehlungen), die Erschließung neuer Märkte durch datenbasierte Services oder die Schaffung eines einzigartigen Wettbewerbsvorteils?",
  '4.7': "Was blockiert die Entwicklung einer eigenen KI-Anwendung am stärksten? Sind es Datenprobleme (-> Datenstrategie entwickeln), fehlendes Know-how (-> Partner suchen/aufbauen), unklarer ROI (-> Business Case rechnen), Datenschutz (-> rechtliche Prüfung/Anonymisierung) oder fehlt die zündende Idee (-> strukturierte Ideation)? Gehen Sie die größte Hürde aktiv an.",
  '4.8': "Skizzieren Sie eine konkrete Idee für eine eigene KI-Anwendung, die auf Ihrem spezifischen Unternehmenswissen oder Ihren Daten basiert. Welches Kunden- oder Mitarbeiterproblem würde sie lösen? Wie würde sie funktionieren und welchen messbaren Mehrwert würde sie generieren (z.B. ein KI-Assistent, der interne Dokumente durchsucht und Fragen beantwortet)?",

  // --- Schritt 5: Langfristige Strategien sicherstellen ---
  '5.1': "Richten Sie einen systematischen Prozess für das Technologie-Scouting ein. Definieren Sie, wer dafür verantwortlich ist, welche Quellen (Fachartikel, Konferenzen, Netzwerke, Anbieter-Roadmaps) regelmäßig beobachtet und wie neue Trends oder Tools auf ihre Relevanz für Ihr Unternehmen bewertet werden.",
  '5.2': "Die KI-Welt ist dynamisch. Bauen Sie Flexibilität in Ihre KI-Strategie ein. Planen Sie feste Zyklen (z.B. halbjährlich), in denen die Strategie überprüft und an neue technologische Entwicklungen oder Marktveränderungen angepasst wird. Agile Methoden können hierbei unterstützen.",
  '5.3': "Betrachten Sie eingeführte KI-Anwendungen nicht als statisch. Implementieren Sie einen Prozess zur kontinuierlichen, datengesteuerten Optimierung. Analysieren Sie regelmäßig Nutzungsdaten, Performance-Metriken und Nutzerfeedback, um Verbesserungspotenziale zu identifizieren und umzusetzen.",
  '5.4': "Schotten Sie sich nicht ab. Nutzen Sie aktiv externe Netzwerke und Wissensquellen. Der Austausch mit Experten, der Besuch von Konferenzen oder die Teilnahme an branchenübergreifenden Communities bringt wertvolle Impulse und hilft, über den Tellerrand zu schauen und von den Erfahrungen anderer zu lernen.",
  '5.5': "Richten Sie den Blick nach vorn. Beschäftigen Sie sich aktiv mit absehbaren zukünftigen Entwicklungen (wie KI-Agenten, die Aufgaben autonom erledigen) und analysieren Sie deren potenzielle Auswirkungen auf Ihre Branche und Ihr Geschäftsmodell. Integrieren Sie diese Erkenntnisse in Ihre langfristige strategische Planung.",
  '5.6': "Die hohe Geschwindigkeit der KI-Entwicklung kann überfordernd wirken. Eine rein abwartende Haltung birgt jedoch Risiken. Entwickeln Sie eine proaktive Strategie: Definieren Sie, wie Sie relevante Informationen filtern, bewerten und in Ihre Planung integrieren, um nicht den Anschluss zu verlieren.",
  '5.7': "Welche Rolle soll KI langfristig in Ihrem Unternehmen spielen? Soll sie primär bestehende Prozesse optimieren und effizienter machen? Oder sehen Sie KI als strategischen Hebel für grundlegende Innovationen, neue Geschäftsmodelle und die Sicherung Ihrer zukünftigen Marktposition? Klären Sie Ihre Ambitionen.",
  '5.8': "Was ist die *eine* wichtigste strategische Weichenstellung, die Sie heute vornehmen müssen, um sicherzustellen, dass Ihr Unternehmen auch in 3-5 Jahren von der KI-Entwicklung profitiert? Ist es der Aufbau interner Datenkompetenz, die Entwicklung strategischer Partnerschaften, die Investition in eine flexible IT-Infrastruktur oder etwas anderes? Priorisieren Sie.",
};